general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = $HOME/.cache/current_wallpaper
    blur_passes = 2
    blur_size = 7
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgb(60, 56, 54)
    inner_color = rgb(40, 40, 40)
    font_color = rgb(235, 219, 178)
    fade_on_empty = true
    placeholder_text = <i>password</i>
    hide_input = false
    check_color = rgb(184, 187, 38)
    fail_color = rgb(251, 73, 52)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    capslock_color = rgb(250, 189, 47)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(235, 219, 178, 1.0)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(168, 153, 132, 1.0)
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 120
    halign = center
    valign = center
}
